# Mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: goo_
  # 配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名（默认别名是类名）
  type-aliases-package:
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Mybatis SQL 打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.zhao.blog.mapper: debug
  config:
  file:
    path:

# 七牛云密钥
qiniu:
  accessKey:
  accessSecretKey:

# spring总配置
spring:
  # 日期格式化
  jackson:
    time-zone: Asia/Shanghai

  # 上传文件大小限制配置
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB

  # es配置
  elasticsearch:
    rest:
      uris:

  # 数据源配置
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url:
      username:
      password:
      filters: stat,wall,log4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    # 超时时间
    timeout: 10000ms
    # 服务器地址
    host:
    # 服务器端口
    port:
    # 数据库
    database:
    # 密码
    password:
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大连接阻塞等待时间
        max-wait: 10000ms
        # 最大空闲连接
        max-idle: 200
        # 最小空闲连接
        min-idle: 5

  # RabbitMQ
  rabbitmq:
    # 服务器地址
    host:
    # 用户名
    username:
    # 密码
    password:
    # 虚拟主机
    virtual-host:
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完再继续下一条消息
        prefetch: 1
        # 启动时是否默认启动容器，默认true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间 默认1000ms
        initial-interval: 1000
        # 重试最大次数，默认3次
        max-attempts: 3
        # 重试最大间隔时间，默认10000ms
        max-interval: 10000
        # 重试间隔的乘数。比如配2.0 第一次等10s，第二次等20s，第三次等40s
        multiplier: 1.0

  profiles: dev

server:
  # 端口
  port: 2235
